// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Review struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"userId"`
	ProductID int64              `json:"productId"`
	Rating    int32              `json:"rating"`
	Comment   pgtype.Text        `json:"comment"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt pgtype.Timestamptz `json:"updatedAt"`
	DeletedAt pgtype.Timestamptz `json:"deletedAt"`
	CreatedBy pgtype.Text        `json:"createdBy"`
}
