// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package sqlc

import (
	"database/sql"
	"time"
)

type Review struct {
	ID        int64
	UserID    int64
	ProductID int64
	Rating    int32
	Comment   sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
	CreatedBy sql.NullString
}
