// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: oauth.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuthUser = `-- name: CreateAuthUser :one
INSERT INTO auth (
    id, email, password_hash, status
) VALUES (
    $1, $2, $3, $4
) RETURNING id, email, password_hash, status, created_at, updated_at, deleted_at
`

type CreateAuthUserParams struct {
	ID           pgtype.UUID `json:"id"`
	Email        pgtype.Text `json:"email"`
	PasswordHash pgtype.Text `json:"passwordHash"`
	Status       string      `json:"status"`
}

func (q *Queries) CreateAuthUser(ctx context.Context, arg CreateAuthUserParams) (Auth, error) {
	row := q.db.QueryRow(ctx, createAuthUser,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.Status,
	)
	var i Auth
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createOAuthProvider = `-- name: CreateOAuthProvider :one
INSERT INTO oauth_providers (
    id, user_id, provider_name, provider_user_id, email, name, 
    access_token, refresh_token, expires_at, scopes
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
) RETURNING id, user_id, provider_name, provider_user_id, email, name, access_token, refresh_token, expires_at, created_at, updated_at
`

type CreateOAuthProviderParams struct {
	ID             pgtype.UUID        `json:"id"`
	UserID         pgtype.UUID        `json:"userId"`
	ProviderName   string             `json:"providerName"`
	ProviderUserID string             `json:"providerUserId"`
	Email          pgtype.Text        `json:"email"`
	Name           pgtype.Text        `json:"name"`
	AccessToken    pgtype.Text        `json:"accessToken"`
	RefreshToken   pgtype.Text        `json:"refreshToken"`
	ExpiresAt      pgtype.Timestamptz `json:"expiresAt"`
	Scopes         []string           `json:"scopes"`
}

type CreateOAuthProviderRow struct {
	ID             pgtype.UUID        `json:"id"`
	UserID         pgtype.UUID        `json:"userId"`
	ProviderName   string             `json:"providerName"`
	ProviderUserID string             `json:"providerUserId"`
	Email          pgtype.Text        `json:"email"`
	Name           pgtype.Text        `json:"name"`
	AccessToken    pgtype.Text        `json:"accessToken"`
	RefreshToken   pgtype.Text        `json:"refreshToken"`
	ExpiresAt      pgtype.Timestamptz `json:"expiresAt"`
	CreatedAt      pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt      pgtype.Timestamptz `json:"updatedAt"`
}

func (q *Queries) CreateOAuthProvider(ctx context.Context, arg CreateOAuthProviderParams) (CreateOAuthProviderRow, error) {
	row := q.db.QueryRow(ctx, createOAuthProvider,
		arg.ID,
		arg.UserID,
		arg.ProviderName,
		arg.ProviderUserID,
		arg.Email,
		arg.Name,
		arg.AccessToken,
		arg.RefreshToken,
		arg.ExpiresAt,
		arg.Scopes,
	)
	var i CreateOAuthProviderRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProviderName,
		&i.ProviderUserID,
		&i.Email,
		&i.Name,
		&i.AccessToken,
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUserProfile = `-- name: CreateUserProfile :one
INSERT INTO user_profiles (
    id, email, name, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, email, name, created_at, updated_at
`

type CreateUserProfileParams struct {
	ID        pgtype.UUID        `json:"id"`
	Email     string             `json:"email"`
	Name      pgtype.Text        `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt pgtype.Timestamptz `json:"updatedAt"`
}

func (q *Queries) CreateUserProfile(ctx context.Context, arg CreateUserProfileParams) (UserProfile, error) {
	row := q.db.QueryRow(ctx, createUserProfile,
		arg.ID,
		arg.Email,
		arg.Name,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i UserProfile
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAuthUserByEmail = `-- name: GetAuthUserByEmail :one
SELECT id, email, password_hash, status, created_at, updated_at, deleted_at
FROM auth
WHERE email = $1
`

func (q *Queries) GetAuthUserByEmail(ctx context.Context, email pgtype.Text) (Auth, error) {
	row := q.db.QueryRow(ctx, getAuthUserByEmail, email)
	var i Auth
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAuthUserByID = `-- name: GetAuthUserByID :one
SELECT id, email, password_hash, status, created_at, updated_at, deleted_at
FROM auth
WHERE id = $1
`

func (q *Queries) GetAuthUserByID(ctx context.Context, id pgtype.UUID) (Auth, error) {
	row := q.db.QueryRow(ctx, getAuthUserByID, id)
	var i Auth
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getOAuthProviderByProviderID = `-- name: GetOAuthProviderByProviderID :one
SELECT id, user_id, provider_name, provider_user_id, email, name, access_token, refresh_token, expires_at, created_at, updated_at
FROM oauth_providers
WHERE provider_name = $1 AND provider_user_id = $2
`

type GetOAuthProviderByProviderIDParams struct {
	ProviderName   string `json:"providerName"`
	ProviderUserID string `json:"providerUserId"`
}

type GetOAuthProviderByProviderIDRow struct {
	ID             pgtype.UUID        `json:"id"`
	UserID         pgtype.UUID        `json:"userId"`
	ProviderName   string             `json:"providerName"`
	ProviderUserID string             `json:"providerUserId"`
	Email          pgtype.Text        `json:"email"`
	Name           pgtype.Text        `json:"name"`
	AccessToken    pgtype.Text        `json:"accessToken"`
	RefreshToken   pgtype.Text        `json:"refreshToken"`
	ExpiresAt      pgtype.Timestamptz `json:"expiresAt"`
	CreatedAt      pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt      pgtype.Timestamptz `json:"updatedAt"`
}

func (q *Queries) GetOAuthProviderByProviderID(ctx context.Context, arg GetOAuthProviderByProviderIDParams) (GetOAuthProviderByProviderIDRow, error) {
	row := q.db.QueryRow(ctx, getOAuthProviderByProviderID, arg.ProviderName, arg.ProviderUserID)
	var i GetOAuthProviderByProviderIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProviderName,
		&i.ProviderUserID,
		&i.Email,
		&i.Name,
		&i.AccessToken,
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserProfileByEmail = `-- name: GetUserProfileByEmail :one
SELECT id, email, name, created_at, updated_at
FROM user_profiles
WHERE email = $1
`

func (q *Queries) GetUserProfileByEmail(ctx context.Context, email string) (UserProfile, error) {
	row := q.db.QueryRow(ctx, getUserProfileByEmail, email)
	var i UserProfile
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAuthUser = `-- name: UpdateAuthUser :one
UPDATE auth
SET
    email = $2,
    status = $3,
    updated_at = $4
WHERE id = $1
RETURNING id, email, password_hash, status, created_at, updated_at, deleted_at
`

type UpdateAuthUserParams struct {
	ID        pgtype.UUID        `json:"id"`
	Email     pgtype.Text        `json:"email"`
	Status    string             `json:"status"`
	UpdatedAt pgtype.Timestamptz `json:"updatedAt"`
}

func (q *Queries) UpdateAuthUser(ctx context.Context, arg UpdateAuthUserParams) (Auth, error) {
	row := q.db.QueryRow(ctx, updateAuthUser,
		arg.ID,
		arg.Email,
		arg.Status,
		arg.UpdatedAt,
	)
	var i Auth
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateOAuthProvider = `-- name: UpdateOAuthProvider :one
UPDATE oauth_providers
SET 
    access_token = $2,
    refresh_token = $3,
    expires_at = $4,
    updated_at = now()
WHERE id = $1
RETURNING id, user_id, provider_name, provider_user_id, email, name, access_token, refresh_token, expires_at, created_at, updated_at
`

type UpdateOAuthProviderParams struct {
	ID           pgtype.UUID        `json:"id"`
	AccessToken  pgtype.Text        `json:"accessToken"`
	RefreshToken pgtype.Text        `json:"refreshToken"`
	ExpiresAt    pgtype.Timestamptz `json:"expiresAt"`
}

type UpdateOAuthProviderRow struct {
	ID             pgtype.UUID        `json:"id"`
	UserID         pgtype.UUID        `json:"userId"`
	ProviderName   string             `json:"providerName"`
	ProviderUserID string             `json:"providerUserId"`
	Email          pgtype.Text        `json:"email"`
	Name           pgtype.Text        `json:"name"`
	AccessToken    pgtype.Text        `json:"accessToken"`
	RefreshToken   pgtype.Text        `json:"refreshToken"`
	ExpiresAt      pgtype.Timestamptz `json:"expiresAt"`
	CreatedAt      pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt      pgtype.Timestamptz `json:"updatedAt"`
}

func (q *Queries) UpdateOAuthProvider(ctx context.Context, arg UpdateOAuthProviderParams) (UpdateOAuthProviderRow, error) {
	row := q.db.QueryRow(ctx, updateOAuthProvider,
		arg.ID,
		arg.AccessToken,
		arg.RefreshToken,
		arg.ExpiresAt,
	)
	var i UpdateOAuthProviderRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProviderName,
		&i.ProviderUserID,
		&i.Email,
		&i.Name,
		&i.AccessToken,
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE user_profiles
SET
    email = $2,
    name = $3,
    updated_at = $4
WHERE id = $1
RETURNING id, email, name, created_at, updated_at
`

type UpdateUserProfileParams struct {
	ID        pgtype.UUID        `json:"id"`
	Email     string             `json:"email"`
	Name      pgtype.Text        `json:"name"`
	UpdatedAt pgtype.Timestamptz `json:"updatedAt"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (UserProfile, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.ID,
		arg.Email,
		arg.Name,
		arg.UpdatedAt,
	)
	var i UserProfile
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
