// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: query.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createReview = `-- name: CreateReview :one
INSERT INTO reviews (user_id, product_id, rating, comment, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, product_id, rating, comment, created_at, updated_at, deleted_at, created_by
`

type CreateReviewParams struct {
	UserID    int64
	ProductID int64
	Rating    int32
	Comment   sql.NullString
	CreatedBy sql.NullString
}

func (q *Queries) CreateReview(ctx context.Context, arg CreateReviewParams) (Review, error) {
	row := q.db.QueryRow(ctx, createReview,
		arg.UserID,
		arg.ProductID,
		arg.Rating,
		arg.Comment,
		arg.CreatedBy,
	)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProductID,
		&i.Rating,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getReview = `-- name: GetReview :one
SELECT id, user_id, product_id, rating, comment, created_at, updated_at, deleted_at, created_by FROM reviews
WHERE id = $1 AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetReview(ctx context.Context, id int64) (Review, error) {
	row := q.db.QueryRow(ctx, getReview, id)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProductID,
		&i.Rating,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
	)
	return i, err
}

const listReviews = `-- name: ListReviews :many
SELECT id, user_id, product_id, rating, comment, created_at, updated_at, deleted_at, created_by FROM reviews
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1
OFFSET $2
`

type ListReviewsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListReviews(ctx context.Context, arg ListReviewsParams) ([]Review, error) {
	rows, err := q.db.Query(ctx, listReviews, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Review
	for rows.Next() {
		var i Review
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProductID,
			&i.Rating,
			&i.Comment,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
