// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateReview(ctx context.Context, arg CreateReviewParams) (Review, error)
	DeleteReview(ctx context.Context, id int64) error
	GetReview(ctx context.Context, id int64) (Review, error)
	ListReviews(ctx context.Context, arg ListReviewsParams) ([]Review, error)
	UpdateReview(ctx context.Context, arg UpdateReviewParams) (Review, error)
}

var _ Querier = (*Queries)(nil)
