// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: review.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReview = `-- name: CreateReview :one
INSERT INTO reviews (
    user_id,
    product_id,
    rating,
    comment,
    created_by
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, user_id, product_id, rating, comment, created_at, updated_at, deleted_at, created_by
`

type CreateReviewParams struct {
	UserID    int64       `json:"userId"`
	ProductID int64       `json:"productId"`
	Rating    int32       `json:"rating"`
	Comment   pgtype.Text `json:"comment"`
	CreatedBy pgtype.Text `json:"createdBy"`
}

func (q *Queries) CreateReview(ctx context.Context, arg CreateReviewParams) (Review, error) {
	row := q.db.QueryRow(ctx, createReview,
		arg.UserID,
		arg.ProductID,
		arg.Rating,
		arg.Comment,
		arg.CreatedBy,
	)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProductID,
		&i.Rating,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
	)
	return i, err
}

const deleteReview = `-- name: DeleteReview :exec
UPDATE reviews
SET deleted_at = NOW()
WHERE id = $1
`

func (q *Queries) DeleteReview(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteReview, id)
	return err
}

const getReview = `-- name: GetReview :one
SELECT id, user_id, product_id, rating, comment, created_at, updated_at, deleted_at, created_by FROM reviews
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetReview(ctx context.Context, id int64) (Review, error) {
	row := q.db.QueryRow(ctx, getReview, id)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProductID,
		&i.Rating,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
	)
	return i, err
}

const listReviews = `-- name: ListReviews :many
SELECT id, user_id, product_id, rating, comment, created_at, updated_at, deleted_at, created_by FROM reviews
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1
OFFSET $2
`

type ListReviewsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListReviews(ctx context.Context, arg ListReviewsParams) ([]Review, error) {
	rows, err := q.db.Query(ctx, listReviews, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Review{}
	for rows.Next() {
		var i Review
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProductID,
			&i.Rating,
			&i.Comment,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReview = `-- name: UpdateReview :one
UPDATE reviews
SET
    rating = COALESCE($2, rating),
    comment = COALESCE($3, comment),
    updated_at = NOW()
WHERE
    id = $1
AND deleted_at IS NULL
RETURNING id, user_id, product_id, rating, comment, created_at, updated_at, deleted_at, created_by
`

type UpdateReviewParams struct {
	ID      int64       `json:"id"`
	Rating  pgtype.Int4 `json:"rating"`
	Comment pgtype.Text `json:"comment"`
}

func (q *Queries) UpdateReview(ctx context.Context, arg UpdateReviewParams) (Review, error) {
	row := q.db.QueryRow(ctx, updateReview, arg.ID, arg.Rating, arg.Comment)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProductID,
		&i.Rating,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
	)
	return i, err
}
